# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: olafurpg/setup-scala@v7
      with:
          java-version: adopt@1.11

    - name: Cache ~/.cache
      uses: actions/cache@v1
      with:
        path: ~/.cache
        key: ${{ runner.os }}-coursier-${{ hashFiles('project/Libs.scala') }}
        restore-keys: |
            ${{ runner.os }}-coursier-

    - name: Cache ~/.sbt
      uses: actions/cache@v1
      with:
        path: ~/.sbt
        key: ${{ runner.os }}-sbt-${{ hashFiles('project/build.properties') }}
        restore-keys: |
          ${{ runner.os }}-sbt-

    - name: Install CS native
      run: |
        curl -fLo cs https://git.io/coursier-cli-linux
        chmod +x cs
        sudo mv cs /usr/local/bin
        cs install --add-channel https://raw.githubusercontent.com/tmtsoftware/apps/master/apps.json

    - name: Install Kotlin
      run: cs launch org.jetbrains.kotlin:kotlin-compiler-embeddable:1.3.71 -- -version
